version: '3.4'

networks:
  chirp-network:
      name: chirp-network

services:
  azure-sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=${DB_PASSWORD}
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    container_name: azure-sql-server
    networks:
      - chirp-network

  chirpwebservice:
    image: minitwit
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: minitwit
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - azure-sql-server
      - grafana
      - prometheus
    networks:
      - chirp-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - chirp-network

  grafana:
    image: grafana/grafana:10.2.4
    ports:
      - "3000:3000"
    networks:
      - chirp-network