version: '3.4'
services:
  azure-sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      - SA_PASSWORD=${DB_PASSWORD}
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    container_name: azure-sql-server
    networks:
      - chirp-network

  chirpwebservice:
    image: ${DOCKER_USERNAME}/minitwitimage:latest
    build:
      context: .
      dockerfile: src/Chirp.WebService/Dockerfile
    container_name: minitwit
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "5000:5000"
    depends_on:
      - azure-sql-server
    networks:
      - chirp-network

networks:
  chirp-network: